name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        part: [0, 1, 2, 3]   # 並列数は適宜調整
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper

      - name: Run tests (part ${{ matrix.part }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python3 scripts/run_split_verify.py \
            --split 4 \
            --index ${{ matrix.part }} \
            -j $(nproc)

      # ❶ 必ず .verify-helper を用意して中身を確認（空でも JSON を置く）
      - name: Ensure .verify-helper exists
        if: always()
        run: |
          mkdir -p .verify-helper
          test -f .verify-helper/timestamps.json || echo '{}' > .verify-helper/timestamps.json
          echo "::group::.verify-helper snapshot (before upload)"
          ls -la .verify-helper || true
          find .verify-helper -maxdepth 2 -type f -print || true
          echo "::endgroup::"

      # ❷ アップロード（同一 run の docs から拾える）
      - name: Upload verify artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verify-helper-${{ matrix.part }}
          path: .verify-helper
          if-no-files-found: error

  docs:
    needs: verify
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read   # ← artifacts を読む権限

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip3 install -U online-judge-verify-helper
          sudo apt-get update && sudo apt-get install -y jq gh

      # ❸ この run の artifact 一覧を REST で可視化（デバッグ用）
      - name: List artifacts via REST
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "run_id=${{ github.run_id }} repo=${{ github.repository }}"
          gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            --paginate | jq -r '.artifacts[] | [.id, .name, .size_in_bytes] | @tsv' || true

      # ❹ パターンで “この run の” 全 verify-helper-* を取得
      #    ※ run-id/repository は指定しない（同一 run の既定挙動を使う）
      - name: Download verify artifacts (pattern)
        uses: actions/download-artifact@v4
        with:
          pattern: verify-helper-*
          path: /tmp/verify-artifacts
          merge-multiple: false

      # ❺ 取れているか可視化
      - name: Show downloaded artifacts
        run: |
          echo "::group::/tmp/verify-artifacts tree"
          ls -R /tmp/verify-artifacts || true
          echo "::endgroup::"

      # ❻ マージして .verify-helper/ に集約
      - name: Merge verify-helper results
        run: |
          mkdir -p .verify-helper
          python3 scripts/merge_verify_results.py

      # ❼ 合流結果で docs 生成（内部 push が失敗しても先へ進む）
      - name: Generate docs (oj-verify docs)
        continue-on-error: true
        run: oj-verify docs

      # ❽ 生成物を退避（.git を除外）
      - name: Stash generated site
        run: |
          mkdir -p /tmp/ojv-site
          rsync -a --delete --exclude ".git" .verify-helper/markdown/ /tmp/ojv-site/
          rm -rf /tmp/ojv-site/.git || true

      # ❾ gh-pages に上書きデプロイ
      - name: Switch to gh-pages
        run: |
          git fetch origin gh-pages || true
          if git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf . || true
          fi

      - name: Commit and push docs
        run: |
          rsync -a --delete --exclude ".git" /tmp/ojv-site/ .
          git add -A
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update docs [skip ci]" || echo "No changes to commit"
          git push origin gh-pages --force
