docs:
  runs-on: ubuntu-latest
  needs: verify
  if: always()
  permissions:
    contents: write
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Generate docs (oj-verify docs)
      continue-on-error: true
      run: oj-verify docs

    - name: Stash generated site
      run: |
        mkdir -p /tmp/ojv-site
        rsync -a --delete .verify-helper/markdown/ /tmp/ojv-site/

    - name: Switch to gh-pages
      run: |
        git fetch origin gh-pages || true
        if git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
          git checkout gh-pages
        else
          git checkout --orphan gh-pages
          git rm -rf . || true
        fi

    - name: Commit and push docs
      run: |
        rsync -a --delete /tmp/ojv-site/ .
        git add -A
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m "Update docs [skip ci]" || echo "No changes to commit"
        git push origin gh-pages --force
