name: verify

on:
  push
  # pull_request:  # PRでも検証したい場合はコメント解除

env:
  # 従来通りに必要なら設定
  YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
  DROPBOX_TOKEN:   ${{ secrets.DROPBOX_TOKEN }}
  GH_PAT:          ${{ secrets.GH_PAT }}        # gh-pages への push に使用
  GITHUB_TOKEN:    ${{ secrets.GITHUB_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      shards: ${{ steps.split.outputs.shards }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0            # oj-verify が履歴参照するため
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - id: list
        name: List C++ tests
        shell: bash
        run: |
          set -eux
          mkdir -p .verify-helper
          # あなたの構成：test/*test.cpp
          mapfile -t FILES < <(git ls-files 'test/*test.cpp' || true)
          printf '%s\n' "${FILES[@]}" > .verify-helper/targets.txt
          echo "count=${#FILES[@]}" >> "$GITHUB_OUTPUT"

      - id: split
        name: Decide shards
        shell: bash
        run: |
          COUNT="${{ steps.list.outputs.count || 0 }}"
          MAX=8
          if [ -z "$COUNT" ] || [ "$COUNT" -lt 1 ]; then COUNT=1; fi
          SHARDS=$(( COUNT < MAX ? COUNT : MAX ))
          printf '[' > shards.json
          for i in $(seq 0 $((SHARDS-1))); do
            printf '"%s"' "$i"
            if [ "$i" -lt $((SHARDS-1)) ]; then printf ','; fi
          done >> shards.json
          printf ']\n' >> shards.json
          echo "shards=$(cat shards.json)" >> "$GITHUB_OUTPUT"

      - name: Upload target list
        uses: actions/upload-artifact@v4
        with:
          name: verify-targets
          path: .verify-helper/targets.txt

  verify-shard:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: ${{ fromJson(needs.prepare.outputs.shards) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: verify-targets
          path: .            # リポジトリ直下に展開（.verify-helper/targets.txt が復元される）

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install oj-verify
        run: pip3 install -U online-judge-verify-helper

      - name: Cache judge data & verify cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/online-judge-tools/library-checker-problems/
            .verify-helper/cache/
          key: verify-${{ hashFiles('.verify-helper/targets.txt') }}-${{ runner.os }}

      - name: Run shard ${{ matrix.shard }}
        shell: bash
        env:
          SHARD: ${{ matrix.shard }}
        run: |
          set -eux
          N_SHARDS=${{ strategy.job-total }}
          awk -v n="$N_SHARDS" -v s="$SHARD" 'NR % n == s' .verify-helper/targets.txt > shard.txt
          cat shard.txt || true

          if [ -s shard.txt ]; then
            # 各ファイルを並列に検証（oj-verify run <file>）
            xargs -r -a shard.txt -P "$(nproc)" -I{} oj-verify run "{}"
          else
            echo "No tests in this shard."
          fi

  publish:
    needs: [prepare, verify-shard]
    # 既定ブランチへの push のときだけ、最終整合 & gh-pages へ push
    if: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install oj-verify
        run: pip3 install -U online-judge-verify-helper

      - name: Cache judge data & verify cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/online-judge-tools/library-checker-problems/
            .verify-helper/cache/
          key: verify-${{ hashFiles('.verify-helper/targets.txt') }}-${{ runner.os }}

      - name: Git identity (for commits/push)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Finalize & publish docs (gh-pages branch)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          DROPBOX_TOKEN:   ${{ secrets.DROPBOX_TOKEN }}
          GITHUB_TOKEN:    ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          # 並列シャード後に一回だけ全体整合（タイムスタンプ等）
          oj-verify all
          # ドキュメント生成 & gh-pages へ push（従来運用と同じ）
          oj-verify docs
