name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # gh-pages に push するには必要
    strategy:
      fail-fast: false
      matrix:
        part: [0, 1, 2, 3]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper

      - name: Run tests (part ${{ matrix.part }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python3 scripts/run_split_verify.py \
            --split 4 \
            --index ${{ matrix.part }} \
            -j $(nproc)

  docs:
    runs-on: ubuntu-latest
    needs: verify
    if: always()   # ← verify が失敗しても必ず実行する
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper

      - name: Generate and push docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: oj-verify docs
