name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        part: [0, 1, 2, 3]   # 並列数は適宜調整
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper

      - name: Run tests (part ${{ matrix.part }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python3 scripts/run_split_verify.py \
            --split 4 \
            --index ${{ matrix.part }} \
            -j $(nproc)

      # アップロード前に中身を確認
      - name: Show .verify-helper before upload
        if: always()
        run: |
          echo "matrix.part=${{ matrix.part }}"
          ls -la .verify-helper || true
          find .verify-helper -maxdepth 2 -type f -print || true

      - name: Ensure .verify-helper exists
        if: always()
        run: |
          mkdir -p .verify-helper
          test -f .verify-helper/timestamps.json || echo '{}' > .verify-helper/timestamps.json

      - name: Upload verify artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: verify-helper-${{ matrix.part }}
          path: .verify-helper
          if-no-files-found: error

  docs:
    needs: verify
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read   # ← artifacts を読むのに必要

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip3 install -U online-judge-verify-helper
          sudo apt-get update && sudo apt-get install -y jq gh

      # REST API で artifact 一覧を確認
      - name: List artifacts via REST
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            --paginate | jq -r '.artifacts[] | [.id, .name, .size_in_bytes] | @tsv'

      # パターンで一括ダウンロード
      - name: Download verify artifacts (pattern)
        uses: actions/download-artifact@v4
        with:
          pattern: verify-helper-*
          path: /tmp/verify-artifacts
          merge-multiple: false

      # 念のため個別フォールバック
      - name: Download verify artifacts (fallback 0)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: verify-helper-0
          path: /tmp/verify-artifacts/verify-helper-0
      - name: Download verify artifacts (fallback 1)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: verify-helper-1
          path: /tmp/verify-artifacts/verify-helper-1
      - name: Download verify artifacts (fallback 2)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: verify-helper-2
          path: /tmp/verify-artifacts/verify-helper-2
      - name: Download verify artifacts (fallback 3)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: verify-helper-3
          path: /tmp/verify-artifacts/verify-helper-3

      - name: Show downloaded artifacts
        run: |
          echo "::group::/tmp/verify-artifacts tree"
          ls -R /tmp/verify-artifacts || true
          echo "::endgroup::"

      - name: Merge verify-helper results
        run: |
          mkdir -p .verify-helper
          python3 scripts/merge_verify_results.py

      - name: Generate docs (oj-verify docs)
        continue-on-error: true
        run: oj-verify docs

      - name: Stash generated site
        run: |
          mkdir -p /tmp/ojv-site
          rsync -a --delete --exclude ".git" .verify-helper/markdown/ /tmp/ojv-site/
          rm -rf /tmp/ojv-site/.git || true

      - name: Switch to gh-pages
        run: |
          git fetch origin gh-pages || true
          if git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf . || true
          fi

      - name: Commit and push docs
        run: |
          rsync -a --delete --exclude ".git" /tmp/ojv-site/ .
          git add -A
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update docs [skip ci]" || echo "No changes to commit"
          git push origin gh-pages --force
